AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Authentication API with Clean Architecture

Parameters:
  Environment:
    Type: String
    Default: hml
    AllowedValues: [hml, prd]

  DBHost:
    Type: String
  DBName:
    Type: String
  DBUser:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  JWTSecret:
    Type: String
    NoEcho: true

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        DB_HOST: !Ref DBHost
        DB_PORT: '3306'
        DB_NAME: !Ref DBName
        DB_USER: !Ref DBUser
        DB_PASSWORD: !Ref DBPassword
        JWT_SECRET: !Ref JWTSecret
        JWT_ALGORITHM: 'HS256'
        JWT_ISSUER: 'serverless-auth'
        JWT_EXPIRATION_MINUTES: '60'
        ENVIRONMENT: !Ref Environment

Resources:

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${AWS::StackName}-dependencies'
      ContentUri: .
      CompatibleRuntimes: [python3.11]
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.11

  AuthApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      Auth:
        DefaultAuthorizer: JwtAuthorizer
        Authorizers:
          JwtAuthorizer:
            JwtConfiguration:
              issuer: serverless-auth
              audience: [api-client]
            IdentitySource: "$request.header.Authorization"

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-auth'
      CodeUri: src/
      Handler: lambda_handler.lambda_handler
      Layers: [!Ref DependenciesLayer]
      Events:
        AuthRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref AuthApi
            Path: /auth
            Method: POST

  ProtectedFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-protected'
      CodeUri: src/
      Handler: protected_handler.lambda_handler
      Events:
        ProtectedRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref AuthApi
            Path: /protected
            Method: GET
            Auth:
              Authorizer: JwtAuthorizer

Outputs:
  AuthFunctionArn:
    Description: Authentication Lambda Function ARN
    Value: !GetAtt AuthFunction.Arn
  
  AuthFunctionName:
    Description: Authentication Lambda Function Name
    Value: !Ref AuthFunction
    
  ApiUrl:
    Value: !Sub 'https://${AuthApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
