# AWS SAM Template (Alternative to Serverless Framework)
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Authentication API with Clean Architecture

Parameters:
  Environment:
    Type: String
    Default: hml
    AllowedValues:
      - hml
      - prd
  
  DBHost:
    Type: String
    Description: RDS MySQL endpoint
  
  DBName:
    Type: String
    Description: Database name
  
  DBUser:
    Type: String
    Description: Database user
  
  DBPassword:
    Type: String
    NoEcho: true
    Description: Database password
  
  JWTSecret:
    Type: String
    NoEcho: true
    Description: JWT secret key

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        DB_HOST: !Ref DBHost
        DB_PORT: '3306'
        DB_NAME: !Ref DBName
        DB_USER: !Ref DBUser
        DB_PASSWORD: !Ref DBPassword
        JWT_SECRET: !Ref JWTSecret
        JWT_ALGORITHM: 'HS256'
        JWT_ISSUER: 'serverless-auth'
        JWT_EXPIRATION_MINUTES: '60'
        ENVIRONMENT: !Ref Environment

Resources:
  # Dependencies Layer
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${AWS::StackName}-dependencies'
      Description: Python dependencies for authentication Lambda
      ContentUri: .
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.11
      BuildArchitecture: x86_64

  # Authentication Lambda Function
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-auth'
      CodeUri: src/
      Handler: lambda_handler.lambda_handler
      Description: Authenticate customer and generate JWT token
      Layers:
        - !Ref DependenciesLayer
    Metadata:
      BuildMethod: python3.11

Outputs:
  AuthFunctionArn:
    Description: Authentication Lambda Function ARN
    Value: !GetAtt AuthFunction.Arn
  
  AuthFunctionName:
    Description: Authentication Lambda Function Name
    Value: !Ref AuthFunction
